### --- Day 4: Giant Squid ---
You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you can see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play bingo?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The submarine has a bingo subsystem to help passengers (currently, you and the giant squid) pass the time. It automatically generates a random order in which to draw numbers and a random set of boards (your puzzle input). For example:

In [386]:
f = open("input4.txt", "r")
inp = f.read().strip().split('\n\n')
f.close()

In [387]:
numbers = [int(n) for n in inp[0].split(',')]

In [388]:
board_inp = inp[1:]

In [389]:
boards = [[[int(n) for n in row.split()] for row in board.split('\n')] for board in board_inp]

In [390]:
boards[-1]

[[1, 93, 61, 43, 39],
 [20, 67, 4, 58, 32],
 [99, 31, 72, 40, 6],
 [88, 19, 42, 52, 49],
 [35, 45, 65, 50, 91]]

In [391]:
import numpy as np
board_arrays = [np.array(b) for b in boards]

In [392]:
board_arrays[0]

array([[62,  5, 77, 94, 75],
       [59, 10, 23, 44, 29],
       [93, 91, 63, 51, 74],
       [22, 14, 15,  2, 55],
       [78, 18, 95, 58, 57]])

In [270]:
for m in range(0,5):
    print(board_arrays[0][m,:].flatten().tolist())

[62, 5, 77, 94, 75]
[59, 10, 23, 44, 29]
[93, 91, 63, 51, 74]
[22, 14, 15, 2, 55]
[78, 18, 95, 58, 57]


In [499]:
board_arrays[0]

array([[62,  5, 77, 94, 75],
       [59, 10, 23, 44, 29],
       [93, 91, 63, 51, 74],
       [22, 14, 15,  2, 55],
       [78, 18, 95, 58, 57]])

In [278]:
def part_one(numbers, board_arrays):
    for n in range(1,len(numbers)):
        called_nums = numbers[:n]
        for ba in board_arrays:
            ba2d = ba.reshape(5, 5)
            for m in range(0,5):
                column = ba2d[:,m]
                column.flatten().tolist()
                if all(nums in called_nums for nums in column):
                    board = ba
                    return part_one_score(board, called_nums)
                row = ba2d[m,:]
                row.flatten().tolist()
                if all(nums in called_nums for nums in row):
                    board = ba
                    return part_one_score(board, called_nums)

In [434]:
def part_one_score(board, called_nums):
    unmarked = [num for num in board.flatten().tolist() if num not in called_nums]
    sum = 0
    for n in unmarked:
        sum = sum + n
    print(board,'\n\n','called:',called_nums,'\n','unmarked:',unmarked,'\n','sum:',sum,'last:', called_nums[-1], 'round:', len(called_nums))
    return sum * called_nums[-1]

In [497]:
part_one(numbers, board_arrays)

[[35 30  9 51 34]
 [98 80 56 62 85]
 [93 36 18 65 12]
 [54 32 26 79 49]
 [ 5 83 41 60 89]] 

 called: [26, 55, 7, 40, 56, 34, 58, 90, 60, 83, 37, 36, 9, 27, 42, 19, 46, 18, 49, 52, 75, 17, 70, 41] 
 unmarked: [35, 30, 51, 98, 80, 62, 85, 93, 65, 12, 54, 32, 79, 5, 89] 
 sum: 870 last: 41 round: 24


35670

In [514]:
def part_two(numbers, boards, i=5):
    for n in range(i,len(numbers)):
        called_nums = numbers[:n]
        for m in range(0,5):
            for k in range(len(boards)-1,-1,-1):
                ba2d = boards[k]
                column = ba2d[:,m]
                column.flatten().tolist()
                row = ba2d[m,:]
                row.flatten().tolist()                 
                if all(elem in called_nums for elem in column):
                    if len(boards) > 1:
                        print(boards[k],'\n')
                        del boards[k]
#                         return part_two(numbers, boards, i=n-1)
                    else:
                        print('winning nr:',called_nums[-1],'\n',boards,'\n')
                        return part_one_score(boards[0], called_nums)
#                     else: return (boards, i, n, len(called_nums), called_nums[-1], called_nums[-2])
                elif all(be in called_nums for be in row):
                    if len(boards) > 1:
                        print(boards[k],'\n')
                        del boards[k]
#                         return part_two(numbers, boards, i=n-1)
                    else:
                        print('winning nr:',called_nums[-1],'\n',boards,'\n')
                        return part_one_score(boards[0], called_nums)
#                     else: return (boards, i, n, len(called_nums), called_nums[-1], called_nums[-2])
    

In [515]:
part_two(numbers, board_arrays.copy())

[[35 30  9 51 34]
 [98 80 56 62 85]
 [93 36 18 65 12]
 [54 32 26 79 49]
 [ 5 83 41 60 89]] 

[[86 85 22 80 64]
 [56 33 25  9 18]
 [52  3 39 63 34]
 [40 91  8 59 60]
 [82 93 35  4  7]] 

[[90 21 80 29  2]
 [19 63 36 48 83]
 [ 0 82 40  1 49]
 [ 4  9 97 54 46]
 [18 95 17 22 42]] 

[[13 14 44 26  4]
 [65 54 98 19 82]
 [ 8 74 72 91 99]
 [32 15 93 95 75]
 [34 52  7 78  2]] 

[[81  8 55 76 58]
 [74 53 16 63 17]
 [30 31 41 72 37]
 [73  4 18 87 34]
 [88 95 21 50 77]] 

[[ 1 93 61 43 39]
 [20 67  4 58 32]
 [99 31 72 40  6]
 [88 19 42 52 49]
 [35 45 65 50 91]] 

[[51 19 95 31 47]
 [59 58 82 12 68]
 [64 79 76 69 87]
 [36 17  1 48 16]
 [70 46 62 83 94]] 

[[10 70 39 85 28]
 [ 9  3 48 95 56]
 [40 34 44 57 31]
 [79 27 97 50 15]
 [32 96  0 82 43]] 

[[34 10 57 94 17]
 [29 76 53  6 27]
 [92 26 18 15 14]
 [71 43 39 62  8]
 [88 32 93  0 25]] 

[[22 25 53 67 87]
 [83 39 11 14 58]
 [70 88 73  8 33]
 [ 0 79 95 27 12]
 [90 75 89 66 24]] 

[[98 13  3 59 37]
 [65 25 73 38  6]
 [40 94 71 11 93]
 [85  8 21 17 26

22704

In [452]:
all(x in [0,1,2,3,4,5] for y in [3,2,1])

True

In [398]:
test = board_arrays.copy()

In [296]:
test.remove(test[0])

In [297]:
test[0]

array([[87, 59, 20, 32, 15],
       [16, 50, 12, 24, 86],
       [14, 37, 72, 63, 92],
       [25, 30, 85, 55, 39],
       [52, 11, 68, 31, 91]])